import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { resultCsv, resultPhotos } from "../../../src/lib/customer-select-result";

test("선택·메모를 검토하고 전달 버전을 고정해 복사·CSV로 내보낸다", async ({ page, context }) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/customer-select/select?scene=0");
  await page.getByRole("button", { name: "ACUT_1_0001.jpg 3장 유사컷 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0001.jpg 최종 선택", exact: true }).click();
  await page.getByRole("button", { name: "사진 2 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0002.jpg 최종 선택", exact: true }).click();
  await page.getByRole("button", { name: "상세보기 닫기" }).click();
  await page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0004.jpg 최종 선택", exact: true }).click();
  await page.getByRole("button", { name: "상세보기 닫기" }).click();
  await page.getByRole("link", { name: /최종 검토/ }).click();
  await expect(page.getByText(/최종 선택 3장 · 목표 60장/)).toBeVisible();
  await expect(page.getByText("장소·소품", { exact: true })).toHaveCount(0);
  await expect(page.getByText(/유사컷 1묶음/)).toBeVisible();
  await expect(page.getByRole("button", { name: "결과 만들기", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0004.jpg 선택 해제", exact: true }).click();
  await page.getByRole("button", { name: "되돌리기" }).click();
  await page.getByRole("button", { name: "ACUT_1_0002.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByLabel("ACUT_1_0002.jpg 요청 사항", { exact: true }).fill('피부는 "자연스럽게"\n배경 정리');
  await page.keyboard.press("Escape");
  await expect(page.getByLabel("요청 사항 있음")).toBeVisible();
  await page.getByRole("button", { name: "결과 만들기", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "이 결과를 만들까요?" })).toContainText("요청 사항이 있는 사진 1장");
  await page.getByRole("button", { name: "결과 만들고 확인하기" }).click();
  await expect(page).toHaveURL(/delivery\?.*v=1/);
  await page.getByRole("button", { name: "파일명 목록 복사", exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("ACUT_1_0001.jpg\nACUT_1_0002.jpg\nACUT_1_0004.jpg");
  await page.getByRole("button", { name: "요청 사항까지 복사", exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('요청: 피부는 "자연스럽게"\n배경 정리');
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "CSV 다운로드" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("A-CUT_셀렉결과_v1.csv");
  const csv = await readFile((await download.path())!, "utf8");
  expect(csv.startsWith("\uFEFF")).toBe(true);
  expect(csv).toContain('"피부는 ""자연스럽게""\n배경 정리"');
  await page.getByRole("link", { name: "공유 결과 미리보기" }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("작가에게 보여줄");
  await expect(page.getByRole("button", { name: "CSV 다운로드" })).toHaveCount(0);
  await page.getByRole("link", { name: "결과 전달로" }).click();
  await page.getByRole("link", { name: "선택·요청 수정하기" }).click();
  await expect(page).toHaveURL(/customer-select\/review/);
  await expect(page.getByRole("heading", { name: "최종 검토" })).toBeVisible();
  await page.getByRole("button", { name: "ACUT_1_0002.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByLabel("ACUT_1_0002.jpg 요청 사항", { exact: true }).fill("새 요청");
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0004.jpg 선택 해제", exact: true }).click();
  await page.getByRole("button", { name: "결과 만들기", exact: true }).click();
  await page.getByRole("button", { name: "결과 만들고 확인하기" }).click();
  await expect(page).toHaveURL(/v=2/);
  await expect(page.getByText("새 요청", { exact: true })).toBeVisible();
  await expect(page.getByText("ACUT_1_0004.jpg", { exact: true })).toHaveCount(0);
  await page.getByLabel("결과 버전", { exact: true }).selectOption("1");
  await expect(page.getByText('피부는 "자연스럽게"\n배경 정리', { exact: true })).toBeVisible();
  await expect(page.getByText("ACUT_1_0004.jpg", { exact: true })).toBeVisible();
  await expect(page.getByText(/이전 결과 v1/)).toBeVisible();
  await page.evaluate(() => Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async () => { throw new Error("denied"); } } }));
  await page.getByRole("button", { name: "파일명 목록 복사", exact: true }).click();
  await expect(page.getByLabel("직접 복사할 결과", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/customer-select-delivery-desktop.png", fullPage: true });
  expect(errors).toEqual([]);
});

test("시작에서 입력한 목표가 업로드·분석·선택·검토까지 이어진다", async ({ page }) => {
  await page.goto("/customer-select/new");
  await page.locator('select[name="shootType"]').selectOption("ceremony");
  const target = page.getByRole("spinbutton", { name: /최종 목표 장수/ });
  await expect(target).toHaveValue("");
  await page.getByRole("textbox", { name: /프로젝트 이름/ }).fill("지우와 민준");
  await target.fill("2");
  await page.getByRole("button", { name: "사진 올리기", exact: true }).click();
  await page.getByRole("button", { name: "검수용 5,000장 예시 보기" }).click();
  await page.getByRole("button", { name: "사진 고르기 시작" }).click();
  await page.getByRole("button", { name: "분석 없이 사진 고르기" }).click();
  await expect(page.getByText("최종 0 / 2장", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "ACUT_1_0001.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0001.jpg 최종 선택", exact: true }).click();
  await page.getByRole("button", { name: "상세보기 닫기" }).click();
  await page.getByRole("link", { name: /최종 검토/ }).click();
  await expect(page.getByText(/최종 선택 1장 · 목표 2장/)).toBeVisible();
  await expect(page.getByText(/지우와 민준/)).toBeVisible();
  await expect(page.getByText(/유사컷 .*묶음/)).toHaveCount(0);
});

test("빈 결과·모바일 검토와 CSV 수식 방어를 확인한다", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/customer-select/delivery?v=8");
  await expect(page.getByRole("heading", { name: "전달 결과가 없어요." })).toBeVisible();
  await page.getByRole("link", { name: "최종 검토로", exact: true }).click();
  await expect(page.getByText("아직 선택한 사진이 없어요.")).toBeVisible();
  await expect(page.getByRole("button", { name: "결과 만들기", exact: true })).toHaveCount(0);
  await page.getByRole("link", { name: "사진 고르기", exact: true }).click();
  await page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "ACUT_1_0004.jpg 최종 선택", exact: true }).click();
  await page.getByRole("button", { name: "상세보기 닫기" }).click();
  await page.getByRole("link", { name: /최종 검토/ }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole("heading", { level: 1, name: "최종 검토" })).toBeVisible();
  await expect.poll(() => page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).locator("img").evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThan(2000);
  await page.screenshot({ path: "test-results/customer-select-review-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "결과 만들기", exact: true }).click();
  await page.getByRole("button", { name: "결과 만들고 확인하기" }).click();
  await expect(page.getByRole("heading", { level: 1, name: "작가에게 전달해 주세요." })).toBeVisible();
  await expect.poll(() => page.getByRole("button", { name: "ACUT_1_0004.jpg 크게 보기", exact: true }).locator("img").evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/customer-select-delivery-mobile.png", fullPage: true });
  const photos = resultPhotos(["0:photo-1", "0:photo-0"]);
  expect(photos.map(photo => photo.filename)).toEqual(["ACUT_1_0001.jpg", "ACUT_1_0002.jpg"]);
  expect(resultCsv(photos, { "0:photo-0": '  =HYPERLINK("x")' }, 1)).toContain('"\'  =HYPERLINK(""x"")"');
});
